name: python-checks

on: pull_request

jobs:
    
  create-venv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      id: cache
      with:
        path: code/backend/venv
        key: ${{ runner.os }}-python-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-venv-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
  flake8:
    needs: create-venv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-python-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-venv-
    - name: Run flake8
      run: |
        source venv/bin/activate
        flake8
        
  mypy:
    needs: create-venv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-python-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-venv-
    - name: Run flake8
      run: |
        mypy *py
